#pragma kernel AvgPool2D_NHWC CHANNELS_FIRST=0
#pragma kernel MaxPool2D_NHWC CHANNELS_FIRST=0
#pragma kernel AvgPool2DReduce_NHWC CHANNELS_FIRST=0
#pragma kernel MaxPool2DReduce_NHWC CHANNELS_FIRST=0
#pragma kernel GlobalAvgPool2D_NHWC CHANNELS_FIRST=0
#pragma kernel GlobalMaxPool2D_NHWC CHANNELS_FIRST=0
#pragma kernel AvgVariancePool2DReduce_NHWC CHANNELS_FIRST=0
#pragma kernel GlobalAvgVariancePool2D_NHWC CHANNELS_FIRST=0

#include "Pool.cginc"
